GetRankingAsync
Xwilarg/BooruSharp pull request #11
Opened 2020-08-23 12:43 UTC by KoB-Kirito

So I added GetRankingAsync. It returns 30 posts from the ranking.

While working on that I also noticed that R-18G posts are not flagged as nsfw.

ToDo:
- request function -> unify requests in one place
- add unit tests

2020-08-23 14:57 UTC, Xwilarg commented on BooruSharp.Others/Pixiv.cs
>                  throw new AuthentificationInvalid();
Authentification is already checked here (line 96), can it really return an empty token?

2020-08-23 14:57 UTC, Xwilarg commented on BooruSharp.Others/Pixiv.cs
> +            if (tags.Contains("R-18G"))
Maybe we should add something in the answer to differenciate the 2 kinds of NSFW content

2020-08-23 16:14 UTC, KoB-Kirito commented on BooruSharp.Others/Pixiv.cs
>                  throw new AuthentificationInvalid();
Oh yeah. While testing it happened that I authentificated with a refreshtoken and it did not throw, but the accessToken was empty. I didn‘t manage to reproduce, but added that to be sure.

2020-08-23 16:18 UTC, KoB-Kirito commented on BooruSharp.Others/Pixiv.cs
> +            if (tags.Contains("R-18G"))
I would rather not change the rating, to keep it consistent with the boorus. You can‘t really use questionable for anything, so you would need to add a new one.
My app for example relies on rating, and I would need to rewrite some parts to accomodate a fourth one.
Another value but rating maybe, like an IsGore flag?

2020-08-23 16:34 UTC, Xwilarg commented on BooruSharp.Others/Pixiv.cs
>                  throw new AuthentificationInvalid();
Did you check if it was returning a status code other than 200?

2020-08-23 16:36 UTC, Xwilarg commented on BooruSharp.Others/Pixiv.cs
> +            if (tags.Contains("R-18G"))
Well we can't really change the search result class (since it's part of ABooru and all the others booru can't handle it)
But maybe we could inherit it and add more fields there?

2020-08-23 16:37 UTC, KoB-Kirito commented on BooruSharp.Others/Pixiv.cs
>                  throw new AuthentificationInvalid();
No, didn‘t thought so far ..

2020-08-23 16:39 UTC, KoB-Kirito commented on BooruSharp.Others/Pixiv.cs
> +            if (tags.Contains("R-18G"))
A PixivResult?

2020-08-23 16:52 UTC, Xwilarg commented on BooruSharp.Others/Pixiv.cs
> +            if (tags.Contains("R-18G"))
Yeah

2020-08-23 19:15 UTC, n-ski commented on BooruSharp.Others/Pixiv.cs
> +            if (String.IsNullOrWhiteSpace(AccessToken))
```suggestion
            if (string.IsNullOrWhiteSpace(AccessToken))
```

2020-08-23 19:18 UTC, n-ski commented on BooruSharp.Others/Pixiv.cs
> +            { RankingMode.R18G_Weekly, "week_r18g" }
```suggestion
            { RankingMode.PopularAmongMaleUsers, "day_male" },
            { RankingMode.PopularAmongFemaleUsers, "day_female" },
            { RankingMode.Original, "week_original" },
            { RankingMode.MangaRookie, "week_rookie" },
            { RankingMode.MangaDaily, "day_manga" },
            { RankingMode.R18Daily, "day_r18" },
            { RankingMode.R18Weekly, "week_r18" },
            { RankingMode.R18PopularAmongMaleUsers, "day_male_r18" },
            { RankingMode.R18PopularAmongFemaleUsers, "day_female_r18" },
            { RankingMode.R18GWeekly, "week_r18g" }
```
As per [Microsoft guidelines](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/capitalization-conventions#capitalization-rules-for-identifiers), PascalCase is the preferred way of naming enum values.

2020-08-23 19:23 UTC, n-ski commented on BooruSharp.Others/Pixiv.cs
> +            R18G_Weekly = 12
```suggestion
            PopularAmongMaleUsers = 3,
            PopularAmongFemaleUsers = 4,
            Original = 5,
            MangaRookie = 6,
            MangaDaily = 7,
            R18Daily = 8,
            R18Weekly = 9,
            R18PopularAmongMaleUsers = 10,
            R18PopularAmongFemaleUsers = 11,
            R18GWeekly = 12
```
As per [Microsoft guidelines](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/capitalization-conventions#capitalization-rules-for-identifiers), PascalCase is the preferred way of naming enum values.
Also explicitly specifying the integer values isn't necessary.

2020-08-26 15:01 UTC, KoB-Kirito commented
I can't find time and leisure atm to do the other parts. Maybe you can merge this for now, so @n-ski can continue on his readability works without worring to fix conflicts about this and I do them later?

2020-09-01 00:34 UTC, Xwilarg commented
To answer your last comment, I don't think we should merge this to master for now, since there are some things we are still unsure of (especially since the master branch will contains the next release)

2020-09-02 16:27 UTC, n-ski commented on BooruSharp.Others/Pixiv.cs
> +            return ParseSearchResults((JArray)json["illusts"]);
```suggestion
            var response = await HttpClient.SendAsync(request, HttpCompletionOption.ResponseHeadersRead);
            
            response.EnsureSuccessStatusCode();
            
            var jsonToken = JsonConvert.DeserializeObject<JToken>(await response.Content.ReadAsStringAsync());
            return ParseSearchResults((JArray)jsonToken["illusts"]);
```

2020-09-02 16:31 UTC, n-ski commented on BooruSharp.Others/Pixiv.cs
> +        static private Dictionary<RankingMode, string> rankingModeValues = new Dictionary<RankingMode, string>
```suggestion
        private static Dictionary<RankingMode, string> _rankingModeValues = new Dictionary<RankingMode, string>
```

2020-09-02 17:55 UTC, KoB-Kirito commented
PR should be up to date now

2020-09-02 18:40 UTC, KoB-Kirito commented
https://app.codacy.com/manual/Xwilarg/BooruSharp/pullRequest?prid=6057005
This is on purpose, it's the format pixiv wants.

2020-09-02 18:59 UTC, Xwilarg commented
You mean for ToString? Can't you specify the culture as a 2nd argument?

2020-09-02 19:11 UTC, KoB-Kirito commented
But I don't want culture?

2020-09-02 19:15 UTC, n-ski commented
There's no upside to explicitly specifying the culture in this case, since format string is specified and it should ignore the formatting the culture provides.

2020-09-02 19:16 UTC, KoB-Kirito commented
It has to be this format, or pixiv won't accept it, so there is no point.

2020-09-02 19:17 UTC, n-ski commented
> It has to be this format, or pixiv won't accept it, so there is no point.

Well that's what I'm saying. Since you provided the custom format string, culture won't matter, should you specify the culture in `ToString()` or not.

2020-09-02 19:23 UTC, KoB-Kirito commented
I wonder if this is what it want's with those overloads. Not sure if that's better though.

2020-09-02 19:24 UTC, n-ski commented on BooruSharp.Others/Pixiv.cs
> +        }
```suggestion
        public Task<SearchResult[]> GetRankingAsync()
        {
            return GetRankingAsync(RankingMode.Daily, 0, null);
        }

        public Task<SearchResult[]> GetRankingAsync(RankingMode mode)
        {
            return GetRankingAsync(mode, 0, null);
        }
```

2020-09-02 19:33 UTC, KoB-Kirito commented
Okay, Codacy is happy now. Just that one thing. How can I silence that?

2020-09-02 20:24 UTC, Xwilarg commented
I disabled the flag since it wasn't relevant

2020-09-07 12:39 UTC, n-ski requested changes
Needs a rebase and XML documentation for `GetRankingAsync` methods, `RankingMode` enum and its values. Refer to the [existing documentation](https://github.com/Xwilarg/BooruSharp/blob/master/BooruSharp/Search/Post/ABooru.cs#L127-L136) for [examples](https://github.com/Xwilarg/BooruSharp/blob/master/BooruSharp/Search/Post/Rating.cs).

2022-01-18 16:40 UTC, Xwilarg commented
Closing this since it is out of date for more than one year

2022-01-18 16:40 UTC, closed without merging