Code refactor and improvements
Xwilarg/BooruSharp pull request #25
Opened 2020-09-14 00:21 UTC by n-ski

An assortment of improvements that I can't be bothered to split into multiple smaller PRs.

**General changes**:
- Changed the signatures of `private protected` helper methods (`GetCommentSearchResult`, `GetPostSearchResult`, etc). Now instead of there being one method that takes `object` parameter, there is two overloads for each of those methods: one overload takes `JToken` parameter, the other takes `XmlNode` parameter. For classes that override these methods, that makes it clear what kind of object they want to work with. For callers, that makes it clear what kind of object they are allowed to pass.
- Fixed incorrect preview URL of `Search.Post.SearchResult` objects created by `Template.Gelbooru`.

**Networking changes**:
- Added `GetResponseAsync(string)` and `GetResponseAsync(Uri)` helper methods in `ABooru` class and pulled `GetResponseAsync(HttpRequestMessage)` helper method from `Pixiv` class up to `ABooru` class.
- Reworked `GetJsonAsync` helper method, now it requires generic type parameter and returns deserialized JSON string into the desired type, intead of the JSON string.
- Fixed `CheckAvailabilityAsync` method, now it properly throws an exception if the service is not available. The method was also made `virtual`, so subclasses can override the default behavior.
- Made sure every `HttpResponseMessage` that is created by calling `GetResponseAsync` method is properly disposed. See [this part](https://archive.is/vhodw#32%) of Steve Gordon's article about `HttpResponseMessage` for more info.

**Pixiv changes**:
- Updated documentation: added missing exceptions and added remaks about required authorization.
- Refactored a bunch of repeated code into separate methods.
- Changed `CheckUpdateTokenAsync` method visibility to `private` since it is used like a helper method throughout the code, now it also checks that the auth tokens are set.
- Fixed `AddFavoriteAsync` and `RemoveFavoriteAsync` methods not updating auth tokens.
- Added a semaphore to make sure only one login request is being processed in case multiple login/auth requests are made. Semaphore also ensures calls to `AccessToken` and `RefreshToken` properties are blocked until current login request is fully processed and tokens are set/refreshed.

2020-09-16 10:50 UTC, KoB-Kirito commented
You have to use the second ctor if you want the semaphore to function as a lock (new SemaphoreSlim(1,1)).

2020-09-16 10:55 UTC, KoB-Kirito commented
Also you don't have to dispose a slim semaphore as it has no unmanaged code unless you access the AvailableWaitHandle, and you don't in this case.
Also having pixiv as a disposable could tempt users to use it in a using block, which is really not how it should be used in most use-cases.

2020-09-16 12:35 UTC, n-ski commented
> You have to use the second ctor if you want the semaphore to function as a lock (new SemaphoreSlim(1,1)).

That constructor is only ever useful if you want to have some of the "locks" on the semaphore initially taken. `new SemaphoreSlim(1, 1)` and `new SemaphoreSlim(1)` will have the same effect and only one thread will be able to enter semaphore. See [example code](https://dotnetfiddle.net/ePr53q) here.

> you don't have to dispose a slim semaphore as it has no unmanaged code unless you access the AvailableWaitHandle

Will be addressed, thank you.

2020-09-16 14:53 UTC, KoB-Kirito commented
![firefox_2020-09-16_16-52-41](https://user-images.githubusercontent.com/51691757/93354243-13f8fe00-f83d-11ea-8157-4a4e5e6717bc.png)
?

2020-09-16 15:08 UTC, n-ski commented
Yeah, the example code is kinda flawed because calls to WriteLine aren't protected. I fixed it.

2020-09-16 16:38 UTC, KoB-Kirito commented on BooruSharp.Others/Pixiv.cs
> +    public class Pixiv : ABooru, IDisposable
As stated, no IDisposable pls.

2020-09-16 18:35 UTC, KoB-Kirito requested changes
Disposable.

2021-02-07 14:00 UTC, n-ski commented
Looking back at this, there's too much stuff going on (breaking a lot of public APIs and whatnot). Will probably split those changes into multiple PRs if I can think of a better way to handle them.

2021-02-07 14:00 UTC, closed without merging