Haiii :3
Xwilarg/BooruSharp pull request #50
Opened 2023-08-21 01:18 UTC by LucioMacarine

It adds a "search autocomplete" feature

like when you're typing in a search box in a booru and it suggests tags for you

documented all my incredible discoveries in this comment because i like talking to myself:
https://github.com/LucioMacarine/BooruSharp/commit/3efd5d8d2fe7fad6bfbb787a89585e362475bbbb#commitcomment-87519255

2023-08-21 08:16 UTC, Xwilarg commented
Thanks for your PR, I'll have a closer look at it tonight (in like 8 hours)

2023-08-21 16:23 UTC, Xwilarg requested changes
Just had a quick look at the code, will try it next, just marked 2 small things for changes

2023-08-21 16:23 UTC, Xwilarg commented on BooruSharp/Booru/ABooru.cs
> +                    _autocompleteUrl = new Uri(BaseUrl + "tags/" + "autocomplete.json");
```suggestion
                    _autocompleteUrl = new Uri(BaseUrl + "tags/autocomplete.json");
```

2023-08-21 16:23 UTC, Xwilarg commented on BooruSharp/Booru/Template/E621.cs
> +                string antecedent_name = item["antecedent_name"].Value<string>();
Please use camelCase for variable names

2023-08-21 16:27 UTC, Xwilarg commented
Oh could I also ask you to update the table ( https://github.com/Xwilarg/BooruSharp#features-availability ) in the README?

2023-08-21 22:21 UTC, LucioMacarine commented
Done.

2023-08-21 22:22 UTC, LucioMacarine commented
Also added an example in the README if you don't mind

2023-08-23 22:00 UTC, Xwilarg commented
Hey sorry late answer, I'll have a last try tomorrow then merge this (+ nuget packages and stuff)

2023-08-26 09:13 UTC, Xwilarg approved these changes

2023-08-26 09:14 UTC, merged